<?xml version="1.0" encoding="UTF-8" ?>
<channelmaps>
    <channelmap name="SD5981_FTC_Channel" siteCount="1" comment="">
        <tester type="S08">
            <testerslot slot="1" instrument="DIO256" />
            <testerslot slot="2" instrument="DIO256" />
            <testerslot slot="3" instrument="DPS128" />
            <testerslot slot="4" instrument="DPS128" />
            <testerslot slot="5" instrument="DPS128" />
            <testerslot slot="6" instrument="DPS128" />
            <testerslot slot="7" instrument="DIO256" />
            <testerslot slot="8" instrument="EMPTY" />
        </tester>
        <channelpins>
            <channelpin enabled="true" pin="DVDD08" channel="DPS5.0...DPS6.127" />
            <channelpin enabled="true" pin="AVDD12_HSS" channel="DPS4.0...DPS4.127" />
            <channelpin enabled="true" pin="AVDD08_HSS" channel="DPS3.51...DPS3.63" />
            <channelpin enabled="true" pin="VDD08_DDR" channel="DPS3.30...DPS3.31" />
            <channelpin enabled="true" pin="VDDIO12_DDR" channel="DPS3.106...DPS3.107" />
            <channelpin enabled="true" pin="AVDD18_PLL_DDR" channel="DPS3.93...DPS3.94" />
            <channelpin enabled="true" pin="DVDD18_IO" channel="DPS3.96...DPS3.97" />
            <channelpin enabled="true" pin="DVDD18_EFUSE" channel="DPS3.101" />
            <channelpin enabled="true" pin="DVDD08_EFUSE" channel="DPS3.104" />
            <channelpin enabled="true" pin="AVDD18_PCIE" channel="DPS3.0...DPS3.1" />
            <channelpin enabled="true" pin="AVDD08_PCIE" channel="DPS3.32...DPS3.33" />
            <channelpin enabled="true" pin="AVDD08_CPPI" channel="DPS3.5...DPS3.6" />
            <channelpin enabled="true" pin="AVDD18_SCPLL" channel="DPS3.35...DPS3.36" />
            <channelpin enabled="true" pin="AVDD08_SCPLL" channel="DPS3.84...DPS3.85" />
            <channelpin enabled="true" pin="AVDD18_TS_0" channel="DPS3.21...DPS3.22" />
            <channelpin enabled="true" pin="AVDD18_TS_1" channel="DPS3.74...DPS3.75" />
            <channelpin enabled="true" pin="LMAG_RX_N0" channel="DIO2.211" />
            <channelpin enabled="true" pin="LMAG_RX_P0" channel="DIO2.210" />
            <channelpin enabled="true" pin="LMAG_RX_N1" channel="DIO2.223" />
            <channelpin enabled="true" pin="LMAG_RX_P1" channel="DIO2.222" />
            <channelpin enabled="true" pin="LMAG_RX_N2" channel="DIO1.241" />
            <channelpin enabled="true" pin="LMAG_RX_P2" channel="DIO1.240" />
            <channelpin enabled="true" pin="LMAG_RX_N3" channel="DIO2.235" />
            <channelpin enabled="true" pin="LMAG_RX_P3" channel="DIO2.234" />
            <channelpin enabled="true" pin="LMAG_RX_N4" channel="DIO1.243" />
            <channelpin enabled="true" pin="LMAG_RX_P4" channel="DIO1.242" />
            <channelpin enabled="true" pin="LMAG_RX_N5" channel="DIO2.255" />
            <channelpin enabled="true" pin="LMAG_RX_P5" channel="DIO2.254" />
            <channelpin enabled="true" pin="LMAG_RX_N6" channel="DIO1.213" />
            <channelpin enabled="true" pin="LMAG_RX_P6" channel="DIO1.212" />
            <channelpin enabled="true" pin="LMAG_RX_N7" channel="DIO2.165" />
            <channelpin enabled="true" pin="LMAG_RX_P7" channel="DIO2.164" />
            <channelpin enabled="true" pin="LMAG_RX_N8" channel="DIO1.217" />
            <channelpin enabled="true" pin="LMAG_RX_P8" channel="DIO1.216" />
            <channelpin enabled="true" pin="LMAG_RX_N9" channel="DIO2.153" />
            <channelpin enabled="true" pin="LMAG_RX_P9" channel="DIO2.152" />
            <channelpin enabled="true" pin="LMAG_RX_N10" channel="DIO1.189" />
            <channelpin enabled="true" pin="LMAG_RX_P10" channel="DIO1.188" />
            <channelpin enabled="true" pin="LMAG_RX_N11" channel="DIO2.243" />
            <channelpin enabled="true" pin="LMAG_RX_P11" channel="DIO2.242" />
            <channelpin enabled="true" pin="LMAG_RX_N12" channel="DIO1.187" />
            <channelpin enabled="true" pin="LMAG_RX_P12" channel="DIO1.186" />
            <channelpin enabled="true" pin="LMAG_RX_N13" channel="DIO1.211" />
            <channelpin enabled="true" pin="LMAG_RX_P13" channel="DIO1.210" />
            <channelpin enabled="true" pin="LMAG_RX_N14" channel="DIO1.155" />
            <channelpin enabled="true" pin="LMAG_RX_P14" channel="DIO1.154" />
            <channelpin enabled="true" pin="LMAG_RX_N15" channel="DIO2.141" />
            <channelpin enabled="true" pin="LMAG_RX_P15" channel="DIO2.140" />
            <channelpin enabled="true" pin="LMAG_RX_N32" channel="DIO1.183" />
            <channelpin enabled="true" pin="LMAG_RX_P32" channel="DIO1.182" />
            <channelpin enabled="true" pin="LMAG_RX_N33" channel="DIO1.227" />
            <channelpin enabled="true" pin="LMAG_RX_P33" channel="DIO1.226" />
            <channelpin enabled="true" pin="LMAG_RX_N34" channel="DIO2.183" />
            <channelpin enabled="true" pin="LMAG_RX_P34" channel="DIO2.182" />
            <channelpin enabled="true" pin="LMAG_RX_N35" channel="DIO1.025" />
            <channelpin enabled="true" pin="LMAG_RX_P35" channel="DIO1.024" />
            <channelpin enabled="true" pin="LMAG_RX_N36" channel="DIO1.251" />
            <channelpin enabled="true" pin="LMAG_RX_P36" channel="DIO1.250" />
            <channelpin enabled="true" pin="LMAG_RX_N37" channel="DIO1.161" />
            <channelpin enabled="true" pin="LMAG_RX_P37" channel="DIO1.160" />
            <channelpin enabled="true" pin="LMAG_RX_N38" channel="DIO1.001" />
            <channelpin enabled="true" pin="LMAG_RX_P38" channel="DIO1.000" />
            <channelpin enabled="true" pin="LMAG_RX_N39" channel="DIO1.125" />
            <channelpin enabled="true" pin="LMAG_RX_P39" channel="DIO1.124" />
            <channelpin enabled="true" pin="LMAG_RX_N24" channel="DIO1.141" />
            <channelpin enabled="true" pin="LMAG_RX_P24" channel="DIO1.140" />
            <channelpin enabled="true" pin="LMAG_RX_N25" channel="DIO1.061" />
            <channelpin enabled="true" pin="LMAG_RX_P25" channel="DIO1.060" />
            <channelpin enabled="true" pin="LMAG_RX_N26" channel="DIO1.207" />
            <channelpin enabled="true" pin="LMAG_RX_P26" channel="DIO1.206" />
            <channelpin enabled="true" pin="LMAG_RX_N27" channel="DIO1.077" />
            <channelpin enabled="true" pin="LMAG_RX_P27" channel="DIO1.076" />
            <channelpin enabled="true" pin="LMAG_RX_N28" channel="DIO1.101" />
            <channelpin enabled="true" pin="LMAG_RX_P28" channel="DIO1.100" />
            <channelpin enabled="true" pin="LMAG_RX_N29" channel="DIO2.195" />
            <channelpin enabled="true" pin="LMAG_RX_P29" channel="DIO2.194" />
            <channelpin enabled="true" pin="LMAG_RX_N30" channel="DIO1.181" />
            <channelpin enabled="true" pin="LMAG_RX_P30" channel="DIO1.180" />
            <channelpin enabled="true" pin="LMAG_RX_N31" channel="DIO1.245" />
            <channelpin enabled="true" pin="LMAG_RX_P31" channel="DIO1.244" />
            <channelpin enabled="true" pin="LMAG_RX_N16" channel="DIO1.223" />
            <channelpin enabled="true" pin="LMAG_RX_P16" channel="DIO1.222" />
            <channelpin enabled="true" pin="LMAG_RX_N17" channel="DIO2.231" />
            <channelpin enabled="true" pin="LMAG_RX_P17" channel="DIO2.230" />
            <channelpin enabled="true" pin="LMAG_RX_N18" channel="DIO1.179" />
            <channelpin enabled="true" pin="LMAG_RX_P18" channel="DIO1.178" />
            <channelpin enabled="true" pin="LMAG_RX_N19" channel="DIO1.085" />
            <channelpin enabled="true" pin="LMAG_RX_P19" channel="DIO1.084" />
            <channelpin enabled="true" pin="LMAG_RX_N20" channel="DIO1.165" />
            <channelpin enabled="true" pin="LMAG_RX_P20" channel="DIO1.164" />
            <channelpin enabled="true" pin="LMAG_RX_N21" channel="DIO1.231" />
            <channelpin enabled="true" pin="LMAG_RX_P21" channel="DIO1.230" />
            <channelpin enabled="true" pin="LMAG_RX_N22" channel="DIO1.219" />
            <channelpin enabled="true" pin="LMAG_RX_P22" channel="DIO1.218" />
            <channelpin enabled="true" pin="LMAG_RX_N23" channel="DIO1.073" />
            <channelpin enabled="true" pin="LMAG_RX_P23" channel="DIO1.072" />
            <channelpin enabled="true" pin="LMAG_RX_N40" channel="DIO1.115" />
            <channelpin enabled="true" pin="LMAG_RX_P40" channel="DIO1.114" />
            <channelpin enabled="true" pin="LMAG_RX_N41" channel="DIO1.175" />
            <channelpin enabled="true" pin="LMAG_RX_P41" channel="DIO1.174" />
            <channelpin enabled="true" pin="LMAG_RX_N42" channel="DIO2.171" />
            <channelpin enabled="true" pin="LMAG_RX_P42" channel="DIO2.170" />
            <channelpin enabled="true" pin="LMAG_RX_N43" channel="DIO1.091" />
            <channelpin enabled="true" pin="LMAG_RX_P43" channel="DIO1.090" />
            <channelpin enabled="true" pin="LMAG_RX_N44" channel="DIO1.185" />
            <channelpin enabled="true" pin="LMAG_RX_P44" channel="DIO1.184" />
            <channelpin enabled="true" pin="LMAG_RX_N45" channel="DIO1.137" />
            <channelpin enabled="true" pin="LMAG_RX_P45" channel="DIO1.136" />
            <channelpin enabled="true" pin="LMAG_RX_N46" channel="DIO1.209" />
            <channelpin enabled="true" pin="LMAG_RX_P46" channel="DIO1.208" />
            <channelpin enabled="true" pin="LMAG_RX_N47" channel="DIO1.221" />
            <channelpin enabled="true" pin="LMAG_RX_P47" channel="DIO1.220" />
            <channelpin enabled="true" pin="FMAG_RX_N0" channel="DIO7.137" />
            <channelpin enabled="true" pin="FMAG_RX_P0" channel="DIO7.136" />
            <channelpin enabled="true" pin="FMAG_RX_N1" channel="DIO7.083" />
            <channelpin enabled="true" pin="FMAG_RX_P1" channel="DIO7.082" />
            <channelpin enabled="true" pin="FMAG_RX_N2" channel="DIO7.107" />
            <channelpin enabled="true" pin="FMAG_RX_P2" channel="DIO7.106" />
            <channelpin enabled="true" pin="FMAG_RX_N3" channel="DIO7.161" />
            <channelpin enabled="true" pin="FMAG_RX_P3" channel="DIO7.160" />
            <channelpin enabled="true" pin="FMAG_RX_N4" channel="DIO7.227" />
            <channelpin enabled="true" pin="FMAG_RX_P4" channel="DIO7.226" />
            <channelpin enabled="true" pin="FMAG_RX_N5" channel="DIO7.199" />
            <channelpin enabled="true" pin="FMAG_RX_P5" channel="DIO7.198" />
            <channelpin enabled="true" pin="FMAG_RX_N6" channel="DIO7.133" />
            <channelpin enabled="true" pin="FMAG_RX_P6" channel="DIO7.132" />
            <channelpin enabled="true" pin="FMAG_RX_N7" channel="DIO7.175" />
            <channelpin enabled="true" pin="FMAG_RX_P7" channel="DIO7.174" />
            <channelpin enabled="true" pin="FMAG_RX_N8" channel="DIO7.075" />
            <channelpin enabled="true" pin="FMAG_RX_P8" channel="DIO7.074" />
            <channelpin enabled="true" pin="FMAG_RX_N9" channel="DIO7.247" />
            <channelpin enabled="true" pin="FMAG_RX_P9" channel="DIO7.246" />
            <channelpin enabled="true" pin="FMAG_RX_N10" channel="DIO7.183" />
            <channelpin enabled="true" pin="FMAG_RX_P10" channel="DIO7.182" />
            <channelpin enabled="true" pin="FMAG_RX_N11" channel="DIO7.049" />
            <channelpin enabled="true" pin="FMAG_RX_P11" channel="DIO7.048" />
            <channelpin enabled="true" pin="FMAG_RX_N20" channel="DIO7.051" />
            <channelpin enabled="true" pin="FMAG_RX_P20" channel="DIO7.050" />
            <channelpin enabled="true" pin="FMAG_RX_N21" channel="DIO7.251" />
            <channelpin enabled="true" pin="FMAG_RX_P21" channel="DIO7.250" />
            <channelpin enabled="true" pin="FMAG_RX_N22" channel="DIO7.207" />
            <channelpin enabled="true" pin="FMAG_RX_P22" channel="DIO7.206" />
            <channelpin enabled="true" pin="FMAG_RX_N23" channel="DIO7.189" />
            <channelpin enabled="true" pin="FMAG_RX_P23" channel="DIO7.188" />
            <channelpin enabled="true" pin="FMAG_RX_N32" channel="DIO7.237" />
            <channelpin enabled="true" pin="FMAG_RX_P32" channel="DIO7.236" />
            <channelpin enabled="true" pin="FMAG_RX_N33" channel="DIO7.067" />
            <channelpin enabled="true" pin="FMAG_RX_P33" channel="DIO7.066" />
            <channelpin enabled="true" pin="FMAG_RX_N34" channel="DIO7.231" />
            <channelpin enabled="true" pin="FMAG_RX_P34" channel="DIO7.230" />
            <channelpin enabled="true" pin="FMAG_RX_N35" channel="DIO7.031" />
            <channelpin enabled="true" pin="FMAG_RX_P35" channel="DIO7.030" />
            <channelpin enabled="true" pin="FMAG_RX_N36" channel="DIO7.135" />
            <channelpin enabled="true" pin="FMAG_RX_P36" channel="DIO7.134" />
            <channelpin enabled="true" pin="FMAG_RX_N37" channel="DIO7.159" />
            <channelpin enabled="true" pin="FMAG_RX_P37" channel="DIO7.158" />
            <channelpin enabled="true" pin="FMAG_RX_N38" channel="DIO7.037" />
            <channelpin enabled="true" pin="FMAG_RX_P38" channel="DIO7.036" />
            <channelpin enabled="true" pin="FMAG_RX_N39" channel="DIO7.007" />
            <channelpin enabled="true" pin="FMAG_RX_P39" channel="DIO7.006" />
            <channelpin enabled="true" pin="FMAG_RX_N19" channel="DIO7.099" />
            <channelpin enabled="true" pin="FMAG_RX_P19" channel="DIO7.098" />
            <channelpin enabled="true" pin="FMAG_RX_N18" channel="DIO7.151" />
            <channelpin enabled="true" pin="FMAG_RX_P18" channel="DIO7.150" />
            <channelpin enabled="true" pin="FMAG_RX_N17" channel="DIO7.229" />
            <channelpin enabled="true" pin="FMAG_RX_P17" channel="DIO7.228" />
            <channelpin enabled="true" pin="FMAG_RX_N16" channel="DIO7.139" />
            <channelpin enabled="true" pin="FMAG_RX_P16" channel="DIO7.138" />
            <channelpin enabled="true" pin="FMAG_RX_N15" channel="DIO7.165" />
            <channelpin enabled="true" pin="FMAG_RX_P15" channel="DIO7.164" />
            <channelpin enabled="true" pin="FMAG_RX_N14" channel="DIO7.235" />
            <channelpin enabled="true" pin="FMAG_RX_P14" channel="DIO7.234" />
            <channelpin enabled="true" pin="FMAG_RX_N13" channel="DIO7.253" />
            <channelpin enabled="true" pin="FMAG_RX_P13" channel="DIO7.252" />
            <channelpin enabled="true" pin="FMAG_RX_N12" channel="DIO7.223" />
            <channelpin enabled="true" pin="FMAG_RX_P12" channel="DIO7.222" />
            <channelpin enabled="true" pin="FMAG_RX_N24" channel="DIO7.097" />
            <channelpin enabled="true" pin="FMAG_RX_P24" channel="DIO7.096" />
            <channelpin enabled="true" pin="FMAG_RX_N25" channel="DIO7.123" />
            <channelpin enabled="true" pin="FMAG_RX_P25" channel="DIO7.122" />
            <channelpin enabled="true" pin="FMAG_RX_N26" channel="DIO7.025" />
            <channelpin enabled="true" pin="FMAG_RX_P26" channel="DIO7.024" />
            <channelpin enabled="true" pin="FMAG_RX_N27" channel="DIO7.081" />
            <channelpin enabled="true" pin="FMAG_RX_P27" channel="DIO7.080" />
            <channelpin enabled="true" pin="FMAG_RX_N28" channel="DIO7.073" />
            <channelpin enabled="true" pin="FMAG_RX_P28" channel="DIO7.072" />
            <channelpin enabled="true" pin="FMAG_RX_N29" channel="DIO7.001" />
            <channelpin enabled="true" pin="FMAG_RX_P29" channel="DIO7.000" />
            <channelpin enabled="true" pin="FMAG_RX_N30" channel="DIO7.093" />
            <channelpin enabled="true" pin="FMAG_RX_P30" channel="DIO7.092" />
            <channelpin enabled="true" pin="FMAG_RX_N31" channel="DIO7.017" />
            <channelpin enabled="true" pin="FMAG_RX_P31" channel="DIO7.016" />
            <channelpin enabled="true" pin="FMAG_RX_N40" channel="DIO7.065" />
            <channelpin enabled="true" pin="FMAG_RX_P40" channel="DIO7.064" />
            <channelpin enabled="true" pin="FMAG_RX_N41" channel="DIO7.101" />
            <channelpin enabled="true" pin="FMAG_RX_P41" channel="DIO7.100" />
            <channelpin enabled="true" pin="FMAG_RX_N42" channel="DIO7.057" />
            <channelpin enabled="true" pin="FMAG_RX_P42" channel="DIO7.056" />
            <channelpin enabled="true" pin="FMAG_RX_N43" channel="DIO7.041" />
            <channelpin enabled="true" pin="FMAG_RX_P43" channel="DIO7.040" />
            <channelpin enabled="true" pin="FMAG_RX_N44" channel="DIO7.053" />
            <channelpin enabled="true" pin="FMAG_RX_P44" channel="DIO7.052" />
            <channelpin enabled="true" pin="FMAG_RX_N45" channel="DIO7.105" />
            <channelpin enabled="true" pin="FMAG_RX_P45" channel="DIO7.104" />
            <channelpin enabled="true" pin="FMAG_RX_N46" channel="DIO7.033" />
            <channelpin enabled="true" pin="FMAG_RX_P46" channel="DIO7.032" />
            <channelpin enabled="true" pin="FMAG_RX_N47" channel="DIO7.077" />
            <channelpin enabled="true" pin="FMAG_RX_P47" channel="DIO7.076" />
            <channelpin enabled="true" pin="ILA_RX_N0" channel="DIO1.131" />
            <channelpin enabled="true" pin="ILA_RX_P0" channel="DIO1.130" />
            <channelpin enabled="true" pin="ILA_RX_N1" channel="DIO7.071" />
            <channelpin enabled="true" pin="ILA_RX_P1" channel="DIO7.070" />
            <channelpin enabled="true" pin="ILA_RX_N2" channel="DIO7.205" />
            <channelpin enabled="true" pin="ILA_RX_P2" channel="DIO7.204" />
            <channelpin enabled="true" pin="ILA_RX_N3" channel="DIO1.197" />
            <channelpin enabled="true" pin="ILA_RX_P3" channel="DIO1.196" />
            <channelpin enabled="true" pin="ILA_RX_N4" channel="DIO7.233" />
            <channelpin enabled="true" pin="ILA_RX_P4" channel="DIO7.232" />
            <channelpin enabled="true" pin="ILA_RX_N5" channel="DIO7.211" />
            <channelpin enabled="true" pin="ILA_RX_P5" channel="DIO7.210" />
            <channelpin enabled="true" pin="ILA_RX_N6" channel="DIO7.095" />
            <channelpin enabled="true" pin="ILA_RX_P6" channel="DIO7.094" />
            <channelpin enabled="true" pin="ILA_RX_N7" channel="DIO7.203" />
            <channelpin enabled="true" pin="ILA_RX_P7" channel="DIO7.202" />
            <channelpin enabled="true" pin="PIE_RX_N0" channel="DIO7.021" />
            <channelpin enabled="true" pin="PIE_RX_P0" channel="DIO7.020" />
            <channelpin enabled="true" pin="PCIE_RX_N0" channel="DIO7.003" />
            <channelpin enabled="true" pin="PCIE_RX_P0" channel="DIO7.002" />
            <channelpin enabled="true" pin="PCIE_RX_N1" channel="DIO7.125" />
            <channelpin enabled="true" pin="PCIE_RX_P1" channel="DIO7.124" />
            <channelpin enabled="true" pin="LMAG_TX_N0" channel="DIO1.205" />
            <channelpin enabled="true" pin="LMAG_TX_P0" channel="DIO1.204" />
            <channelpin enabled="true" pin="LMAG_TX_N1" channel="DIO1.253" />
            <channelpin enabled="true" pin="LMAG_TX_P1" channel="DIO1.252" />
            <channelpin enabled="true" pin="LMAG_TX_N2" channel="DIO2.129" />
            <channelpin enabled="true" pin="LMAG_TX_P2" channel="DIO2.128" />
            <channelpin enabled="true" pin="LMAG_TX_N3" channel="DIO1.145" />
            <channelpin enabled="true" pin="LMAG_TX_P3" channel="DIO1.144" />
            <channelpin enabled="true" pin="LMAG_TX_N4" channel="DIO1.199" />
            <channelpin enabled="true" pin="LMAG_TX_P4" channel="DIO1.198" />
            <channelpin enabled="true" pin="LMAG_TX_N5" channel="DIO1.177" />
            <channelpin enabled="true" pin="LMAG_TX_P5" channel="DIO1.176" />
            <channelpin enabled="true" pin="LMAG_TX_N6" channel="DIO1.167" />
            <channelpin enabled="true" pin="LMAG_TX_P6" channel="DIO1.166" />
            <channelpin enabled="true" pin="LMAG_TX_N7" channel="DIO1.247" />
            <channelpin enabled="true" pin="LMAG_TX_P7" channel="DIO1.246" />
            <channelpin enabled="true" pin="LMAG_TX_N8" channel="DIO1.249" />
            <channelpin enabled="true" pin="LMAG_TX_P8" channel="DIO1.248" />
            <channelpin enabled="true" pin="LMAG_TX_N9" channel="DIO1.255" />
            <channelpin enabled="true" pin="LMAG_TX_P9" channel="DIO1.254" />
            <channelpin enabled="true" pin="LMAG_TX_N10" channel="DIO1.229" />
            <channelpin enabled="true" pin="LMAG_TX_P10" channel="DIO1.228" />
            <channelpin enabled="true" pin="LMAG_TX_N11" channel="DIO2.247" />
            <channelpin enabled="true" pin="LMAG_TX_P11" channel="DIO2.246" />
            <channelpin enabled="true" pin="LMAG_TX_N12" channel="DIO1.225" />
            <channelpin enabled="true" pin="LMAG_TX_P12" channel="DIO1.224" />
            <channelpin enabled="true" pin="LMAG_TX_N13" channel="DIO1.133" />
            <channelpin enabled="true" pin="LMAG_TX_P13" channel="DIO1.132" />
            <channelpin enabled="true" pin="LMAG_TX_N14" channel="DIO1.201" />
            <channelpin enabled="true" pin="LMAG_TX_P14" channel="DIO1.200" />
            <channelpin enabled="true" pin="LMAG_TX_N15" channel="DIO1.237" />
            <channelpin enabled="true" pin="LMAG_TX_P15" channel="DIO1.236" />
            <channelpin enabled="true" pin="LMAG_TX_N32" channel="DIO1.173" />
            <channelpin enabled="true" pin="LMAG_TX_P32" channel="DIO1.172" />
            <channelpin enabled="true" pin="LMAG_TX_N33" channel="DIO1.149" />
            <channelpin enabled="true" pin="LMAG_TX_P33" channel="DIO1.148" />
            <channelpin enabled="true" pin="LMAG_TX_N34" channel="DIO1.079" />
            <channelpin enabled="true" pin="LMAG_TX_P34" channel="DIO1.078" />
            <channelpin enabled="true" pin="LMAG_TX_N35" channel="DIO1.127" />
            <channelpin enabled="true" pin="LMAG_TX_P35" channel="DIO1.126" />
            <channelpin enabled="true" pin="LMAG_TX_N36" channel="DIO1.171" />
            <channelpin enabled="true" pin="LMAG_TX_P36" channel="DIO1.170" />
            <channelpin enabled="true" pin="LMAG_TX_N37" channel="DIO1.239" />
            <channelpin enabled="true" pin="LMAG_TX_P37" channel="DIO1.238" />
            <channelpin enabled="true" pin="LMAG_TX_N38" channel="DIO1.037" />
            <channelpin enabled="true" pin="LMAG_TX_P38" channel="DIO1.036" />
            <channelpin enabled="true" pin="LMAG_TX_N39" channel="DIO1.013" />
            <channelpin enabled="true" pin="LMAG_TX_P39" channel="DIO1.012" />
            <channelpin enabled="true" pin="LMAG_TX_N24" channel="DIO1.235" />
            <channelpin enabled="true" pin="LMAG_TX_P24" channel="DIO1.234" />
            <channelpin enabled="true" pin="LMAG_TX_N25" channel="DIO1.157" />
            <channelpin enabled="true" pin="LMAG_TX_P25" channel="DIO1.156" />
            <channelpin enabled="true" pin="LMAG_TX_N26" channel="DIO1.203" />
            <channelpin enabled="true" pin="LMAG_TX_P26" channel="DIO1.202" />
            <channelpin enabled="true" pin="LMAG_TX_N27" channel="DIO1.169" />
            <channelpin enabled="true" pin="LMAG_TX_P27" channel="DIO1.168" />
            <channelpin enabled="true" pin="LMAG_TX_N28" channel="DIO1.153" />
            <channelpin enabled="true" pin="LMAG_TX_P28" channel="DIO1.152" />
            <channelpin enabled="true" pin="LMAG_TX_N29" channel="DIO1.191" />
            <channelpin enabled="true" pin="LMAG_TX_P29" channel="DIO1.190" />
            <channelpin enabled="true" pin="LMAG_TX_N30" channel="DIO1.215" />
            <channelpin enabled="true" pin="LMAG_TX_P30" channel="DIO1.214" />
            <channelpin enabled="true" pin="LMAG_TX_N31" channel="DIO2.219" />
            <channelpin enabled="true" pin="LMAG_TX_P31" channel="DIO2.218" />
            <channelpin enabled="true" pin="LMAG_TX_N16" channel="DIO1.089" />
            <channelpin enabled="true" pin="LMAG_TX_P16" channel="DIO1.088" />
            <channelpin enabled="true" pin="LMAG_TX_N17" channel="DIO2.207" />
            <channelpin enabled="true" pin="LMAG_TX_P17" channel="DIO2.206" />
            <channelpin enabled="true" pin="LMAG_TX_N18" channel="DIO1.195" />
            <channelpin enabled="true" pin="LMAG_TX_P18" channel="DIO1.194" />
            <channelpin enabled="true" pin="LMAG_TX_N19" channel="DIO1.129" />
            <channelpin enabled="true" pin="LMAG_TX_P19" channel="DIO1.128" />
            <channelpin enabled="true" pin="LMAG_TX_N20" channel="DIO1.113" />
            <channelpin enabled="true" pin="LMAG_TX_P20" channel="DIO1.112" />
            <channelpin enabled="true" pin="LMAG_TX_N21" channel="DIO1.049" />
            <channelpin enabled="true" pin="LMAG_TX_P21" channel="DIO1.048" />
            <channelpin enabled="true" pin="LMAG_TX_N22" channel="DIO1.193" />
            <channelpin enabled="true" pin="LMAG_TX_P22" channel="DIO1.192" />
            <channelpin enabled="true" pin="LMAG_TX_N23" channel="DIO1.233" />
            <channelpin enabled="true" pin="LMAG_TX_P23" channel="DIO1.232" />
            <channelpin enabled="true" pin="LMAG_TX_N40" channel="DIO7.209" />
            <channelpin enabled="true" pin="LMAG_TX_P40" channel="DIO7.208" />
            <channelpin enabled="true" pin="LMAG_TX_N41" channel="DIO1.163" />
            <channelpin enabled="true" pin="LMAG_TX_P41" channel="DIO1.162" />
            <channelpin enabled="true" pin="LMAG_TX_N42" channel="DIO7.047" />
            <channelpin enabled="true" pin="LMAG_TX_P42" channel="DIO7.046" />
            <channelpin enabled="true" pin="LMAG_TX_N43" channel="DIO7.119" />
            <channelpin enabled="true" pin="LMAG_TX_P43" channel="DIO7.118" />
            <channelpin enabled="true" pin="LMAG_TX_N44" channel="DIO1.103" />
            <channelpin enabled="true" pin="LMAG_TX_P44" channel="DIO1.102" />
            <channelpin enabled="true" pin="LMAG_TX_N45" channel="DIO1.143" />
            <channelpin enabled="true" pin="LMAG_TX_P45" channel="DIO1.142" />
            <channelpin enabled="true" pin="LMAG_TX_N46" channel="DIO1.139" />
            <channelpin enabled="true" pin="LMAG_TX_P46" channel="DIO1.138" />
            <channelpin enabled="true" pin="LMAG_TX_N47" channel="DIO1.151" />
            <channelpin enabled="true" pin="LMAG_TX_P47" channel="DIO1.150" />
            <channelpin enabled="true" pin="FMAG_TX_N0" channel="DIO7.239" />
            <channelpin enabled="true" pin="FMAG_TX_P0" channel="DIO7.238" />
            <channelpin enabled="true" pin="FMAG_TX_N1" channel="DIO7.221" />
            <channelpin enabled="true" pin="FMAG_TX_P1" channel="DIO7.220" />
            <channelpin enabled="true" pin="FMAG_TX_N2" channel="DIO7.023" />
            <channelpin enabled="true" pin="FMAG_TX_P2" channel="DIO7.022" />
            <channelpin enabled="true" pin="FMAG_TX_N3" channel="DIO7.187" />
            <channelpin enabled="true" pin="FMAG_TX_P3" channel="DIO7.186" />
            <channelpin enabled="true" pin="FMAG_TX_N4" channel="DIO7.149" />
            <channelpin enabled="true" pin="FMAG_TX_P4" channel="DIO7.148" />
            <channelpin enabled="true" pin="FMAG_TX_N5" channel="DIO7.185" />
            <channelpin enabled="true" pin="FMAG_TX_P5" channel="DIO7.184" />
            <channelpin enabled="true" pin="FMAG_TX_N6" channel="DIO7.249" />
            <channelpin enabled="true" pin="FMAG_TX_P6" channel="DIO7.248" />
            <channelpin enabled="true" pin="FMAG_TX_N7" channel="DIO7.191" />
            <channelpin enabled="true" pin="FMAG_TX_P7" channel="DIO7.190" />
            <channelpin enabled="true" pin="FMAG_TX_N8" channel="DIO7.079" />
            <channelpin enabled="true" pin="FMAG_TX_P8" channel="DIO7.078" />
            <channelpin enabled="true" pin="FMAG_TX_N9" channel="DIO7.219" />
            <channelpin enabled="true" pin="FMAG_TX_P9" channel="DIO7.218" />
            <channelpin enabled="true" pin="FMAG_TX_N10" channel="DIO7.179" />
            <channelpin enabled="true" pin="FMAG_TX_P10" channel="DIO7.178" />
            <channelpin enabled="true" pin="FMAG_TX_N11" channel="DIO7.055" />
            <channelpin enabled="true" pin="FMAG_TX_P11" channel="DIO7.054" />
            <channelpin enabled="true" pin="FMAG_TX_N20" channel="DIO7.147" />
            <channelpin enabled="true" pin="FMAG_TX_P20" channel="DIO7.146" />
            <channelpin enabled="true" pin="FMAG_TX_N21" channel="DIO7.177" />
            <channelpin enabled="true" pin="FMAG_TX_P21" channel="DIO7.176" />
            <channelpin enabled="true" pin="FMAG_TX_N22" channel="DIO7.225" />
            <channelpin enabled="true" pin="FMAG_TX_P22" channel="DIO7.224" />
            <channelpin enabled="true" pin="FMAG_TX_N23" channel="DIO7.109" />
            <channelpin enabled="true" pin="FMAG_TX_P23" channel="DIO7.108" />
            <channelpin enabled="true" pin="FMAG_TX_N32" channel="DIO7.087" />
            <channelpin enabled="true" pin="FMAG_TX_P32" channel="DIO7.086" />
            <channelpin enabled="true" pin="FMAG_TX_N33" channel="DIO7.171" />
            <channelpin enabled="true" pin="FMAG_TX_P33" channel="DIO7.170" />
            <channelpin enabled="true" pin="FMAG_TX_N34" channel="DIO7.167" />
            <channelpin enabled="true" pin="FMAG_TX_P34" channel="DIO7.166" />
            <channelpin enabled="true" pin="FMAG_TX_N35" channel="DIO7.061" />
            <channelpin enabled="true" pin="FMAG_TX_P35" channel="DIO7.060" />
            <channelpin enabled="true" pin="FMAG_TX_N36" channel="DIO7.063" />
            <channelpin enabled="true" pin="FMAG_TX_P36" channel="DIO7.062" />
            <channelpin enabled="true" pin="FMAG_TX_N37" channel="DIO7.195" />
            <channelpin enabled="true" pin="FMAG_TX_P37" channel="DIO7.194" />
            <channelpin enabled="true" pin="FMAG_TX_N38" channel="DIO7.181" />
            <channelpin enabled="true" pin="FMAG_TX_P38" channel="DIO7.180" />
            <channelpin enabled="true" pin="FMAG_TX_N39" channel="DIO7.201" />
            <channelpin enabled="true" pin="FMAG_TX_P39" channel="DIO7.200" />
            <channelpin enabled="true" pin="FMAG_TX_N19" channel="DIO7.169" />
            <channelpin enabled="true" pin="FMAG_TX_P19" channel="DIO7.168" />
            <channelpin enabled="true" pin="FMAG_TX_N18" channel="DIO7.163" />
            <channelpin enabled="true" pin="FMAG_TX_P18" channel="DIO7.162" />
            <channelpin enabled="true" pin="FMAG_TX_N17" channel="DIO7.241" />
            <channelpin enabled="true" pin="FMAG_TX_P17" channel="DIO7.240" />
            <channelpin enabled="true" pin="FMAG_TX_N16" channel="DIO7.155" />
            <channelpin enabled="true" pin="FMAG_TX_P16" channel="DIO7.154" />
            <channelpin enabled="true" pin="FMAG_TX_N15" channel="DIO7.157" />
            <channelpin enabled="true" pin="FMAG_TX_P15" channel="DIO7.156" />
            <channelpin enabled="true" pin="FMAG_TX_N14" channel="DIO7.143" />
            <channelpin enabled="true" pin="FMAG_TX_P14" channel="DIO7.142" />
            <channelpin enabled="true" pin="FMAG_TX_N13" channel="DIO7.145" />
            <channelpin enabled="true" pin="FMAG_TX_P13" channel="DIO7.144" />
            <channelpin enabled="true" pin="FMAG_TX_N12" channel="DIO7.131" />
            <channelpin enabled="true" pin="FMAG_TX_P12" channel="DIO7.130" />
            <channelpin enabled="true" pin="FMAG_TX_N24" channel="DIO7.039" />
            <channelpin enabled="true" pin="FMAG_TX_P24" channel="DIO7.038" />
            <channelpin enabled="true" pin="FMAG_TX_N25" channel="DIO7.113" />
            <channelpin enabled="true" pin="FMAG_TX_P25" channel="DIO7.112" />
            <channelpin enabled="true" pin="FMAG_TX_N26" channel="DIO7.117" />
            <channelpin enabled="true" pin="FMAG_TX_P26" channel="DIO7.116" />
            <channelpin enabled="true" pin="FMAG_TX_N27" channel="DIO7.029" />
            <channelpin enabled="true" pin="FMAG_TX_P27" channel="DIO7.028" />
            <channelpin enabled="true" pin="FMAG_TX_N28" channel="DIO7.027" />
            <channelpin enabled="true" pin="FMAG_TX_P28" channel="DIO7.026" />
            <channelpin enabled="true" pin="FMAG_TX_N29" channel="DIO7.045" />
            <channelpin enabled="true" pin="FMAG_TX_P29" channel="DIO7.044" />
            <channelpin enabled="true" pin="FMAG_TX_N30" channel="DIO7.069" />
            <channelpin enabled="true" pin="FMAG_TX_P30" channel="DIO7.068" />
            <channelpin enabled="true" pin="FMAG_TX_N31" channel="DIO7.089" />
            <channelpin enabled="true" pin="FMAG_TX_P31" channel="DIO7.088" />
            <channelpin enabled="true" pin="FMAG_TX_N40" channel="DIO7.141" />
            <channelpin enabled="true" pin="FMAG_TX_P40" channel="DIO7.140" />
            <channelpin enabled="true" pin="FMAG_TX_N41" channel="DIO7.153" />
            <channelpin enabled="true" pin="FMAG_TX_P41" channel="DIO7.152" />
            <channelpin enabled="true" pin="FMAG_TX_N42" channel="DIO7.019" />
            <channelpin enabled="true" pin="FMAG_TX_P42" channel="DIO7.018" />
            <channelpin enabled="true" pin="FMAG_TX_N43" channel="DIO7.111" />
            <channelpin enabled="true" pin="FMAG_TX_P43" channel="DIO7.110" />
            <channelpin enabled="true" pin="FMAG_TX_N44" channel="DIO7.121" />
            <channelpin enabled="true" pin="FMAG_TX_P44" channel="DIO7.120" />
            <channelpin enabled="true" pin="FMAG_TX_N45" channel="DIO7.085" />
            <channelpin enabled="true" pin="FMAG_TX_P45" channel="DIO7.084" />
            <channelpin enabled="true" pin="FMAG_TX_N46" channel="DIO7.013" />
            <channelpin enabled="true" pin="FMAG_TX_P46" channel="DIO7.012" />
            <channelpin enabled="true" pin="FMAG_TX_N47" channel="DIO7.005" />
            <channelpin enabled="true" pin="FMAG_TX_P47" channel="DIO7.004" />
            <channelpin enabled="true" pin="ILA_TX_N0" channel="DIO7.245" />
            <channelpin enabled="true" pin="ILA_TX_P0" channel="DIO7.244" />
            <channelpin enabled="true" pin="ILA_TX_N1" channel="DIO7.011" />
            <channelpin enabled="true" pin="ILA_TX_P1" channel="DIO7.010" />
            <channelpin enabled="true" pin="ILA_TX_N2" channel="DIO7.197" />
            <channelpin enabled="true" pin="ILA_TX_P2" channel="DIO7.196" />
            <channelpin enabled="true" pin="ILA_TX_N3" channel="DIO7.215" />
            <channelpin enabled="true" pin="ILA_TX_P3" channel="DIO7.214" />
            <channelpin enabled="true" pin="ILA_TX_N4" channel="DIO7.217" />
            <channelpin enabled="true" pin="ILA_TX_P4" channel="DIO7.216" />
            <channelpin enabled="true" pin="ILA_TX_N5" channel="DIO7.173" />
            <channelpin enabled="true" pin="ILA_TX_P5" channel="DIO7.172" />
            <channelpin enabled="true" pin="ILA_TX_N6" channel="DIO7.193" />
            <channelpin enabled="true" pin="ILA_TX_P6" channel="DIO7.192" />
            <channelpin enabled="true" pin="ILA_TX_N7" channel="DIO7.059" />
            <channelpin enabled="true" pin="ILA_TX_P7" channel="DIO7.058" />
            <channelpin enabled="true" pin="PIE_TX_N0" channel="DIO7.015" />
            <channelpin enabled="true" pin="PIE_TX_P0" channel="DIO7.014" />
            <channelpin enabled="true" pin="PCIE_TX_N0" channel="DIO7.009" />
            <channelpin enabled="true" pin="PCIE_TX_P0" channel="DIO7.008" />
            <channelpin enabled="true" pin="PCIE_TX_N1" channel="DIO7.127" />
            <channelpin enabled="true" pin="PCIE_TX_P1" channel="DIO7.126" />
            <channelpin enabled="true" pin="EMEM_DDR_A0" channel="DIO2.096" />
            <channelpin enabled="true" pin="EMEM_DDR_A1" channel="DIO2.091" />
            <channelpin enabled="true" pin="EMEM_DDR_A2" channel="DIO2.241" />
            <channelpin enabled="true" pin="EMEM_DDR_A3" channel="DIO2.035" />
            <channelpin enabled="true" pin="EMEM_DDR_A4" channel="DIO2.033" />
            <channelpin enabled="true" pin="EMEM_DDR_A5" channel="DIO2.090" />
            <channelpin enabled="true" pin="EMEM_DDR_A6" channel="DIO2.085" />
            <channelpin enabled="true" pin="EMEM_DDR_A7" channel="DIO2.253" />
            <channelpin enabled="true" pin="EMEM_DDR_A8" channel="DIO2.034" />
            <channelpin enabled="true" pin="EMEM_DDR_A9" channel="DIO2.038" />
            <channelpin enabled="true" pin="EMEM_DDR_A10" channel="DIO2.084" />
            <channelpin enabled="true" pin="EMEM_DDR_A11" channel="DIO2.252" />
            <channelpin enabled="true" pin="EMEM_DDR_A12" channel="DIO2.047" />
            <channelpin enabled="true" pin="EMEM_DDR_A13" channel="DIO2.040" />
            <channelpin enabled="true" pin="EMEM_DDR_A14" channel="DIO2.079" />
            <channelpin enabled="true" pin="EMEM_DDR_A15" channel="DIO2.053" />
            <channelpin enabled="true" pin="EMEM_DDR_ALERT_AC_N0" channel="DIO2.029" />
            <channelpin enabled="true" pin="EMEM_DDR_ALERT_AC_N1" channel="DIO2.026" />
            <channelpin enabled="true" pin="EMEM_DDR_BA0" channel="DIO2.072" />
            <channelpin enabled="true" pin="EMEM_DDR_BA1" channel="DIO2.067" />
            <channelpin enabled="true" pin="EMEM_DDR_BA2" channel="DIO2.052" />
            <channelpin enabled="true" pin="EMEM_DDR_BG1" channel="DIO2.059" />
            <channelpin enabled="true" pin="EMEM_DDR_CAS_N" channel="DIO2.046" />
            <channelpin enabled="true" pin="EMEM_DDR_CK_N0" channel="DIO2.137" />
            <channelpin enabled="true" pin="EMEM_DDR_CK_N1" channel="DIO2.131" />
            <channelpin enabled="true" pin="EMEM_DDR_CK_P0" channel="DIO2.136" />
            <channelpin enabled="true" pin="EMEM_DDR_CK_P1" channel="DIO2.130" />
            <channelpin enabled="true" pin="EMEM_DDR_CKE" channel="DIO2.097" />
            <channelpin enabled="true" pin="EMEM_DDR_CS_N0" channel="DIO2.028" />
            <channelpin enabled="true" pin="EMEM_DDR_CS_N1" channel="DIO2.142" />
            <channelpin enabled="true" pin="EMEM_DDR_DBI_N0" channel="DIO2.017" />
            <channelpin enabled="true" pin="EMEM_DDR_DBI_N1" channel="DIO2.011" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ0" channel="DIO2.027" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ1" channel="DIO2.021" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ2" channel="DIO2.032" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ3" channel="DIO2.005" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ4" channel="DIO2.045" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ5" channel="DIO2.039" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ6" channel="DIO2.041" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ7" channel="DIO2.044" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ8" channel="DIO2.023" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ9" channel="DIO2.004" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ10" channel="DIO2.010" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ11" channel="DIO2.148" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ12" channel="DIO2.016" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ13" channel="DIO2.154" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ14" channel="DIO2.149" />
            <channelpin enabled="true" pin="EMEM_DDR_DQ15" channel="DIO2.155" />
            <channelpin enabled="true" pin="EMEM_DDR_DQS_N0" channel="DIO2.229" />
            <channelpin enabled="true" pin="EMEM_DDR_DQS_N1" channel="DIO2.217" />
            <channelpin enabled="true" pin="EMEM_DDR_DQS_P0" channel="DIO2.228" />
            <channelpin enabled="true" pin="EMEM_DDR_DQS_P1" channel="DIO2.216" />
            <channelpin enabled="true" pin="EMEM_DDR_ODT0" channel="DIO2.102" />
            <channelpin enabled="true" pin="EMEM_DDR_ODT1" channel="DIO2.143" />
            <channelpin enabled="true" pin="EMEM_DDR_RAS_N" channel="DIO2.073" />
            <channelpin enabled="true" pin="EMEM_DDR_RST_N" channel="DIO2.022" />
            <channelpin enabled="true" pin="EMEM_DDR_WE_N" channel="DIO2.078" />
            <channelpin enabled="true" pin="EMEM_DDR_DBG_DTO0" channel="DIO1.004" />
            <channelpin enabled="true" pin="EMEM_DDR_DBG_DTO1" channel="DIO1.005" />
            <channelpin enabled="false" pin="EMEM_DDR_ZCOMP" channel="DIO7.042" />
            <channelpin enabled="true" pin="JTAG_TCK" channel="DIO2.002" />
            <channelpin enabled="true" pin="JTAG_TDO" channel="DIO2.003" />
            <channelpin enabled="true" pin="JTAG_TMS" channel="DIO2.008" />
            <channelpin enabled="true" pin="JTAG_TRSTN" channel="DIO2.009" />
            <channelpin enabled="true" pin="JTAG_TDI" channel="DIO2.014" />
            <channelpin enabled="true" pin="JTAG_CE_N" channel="DIO2.015" />
            <channelpin enabled="true" pin="JTAG_CE_OUT" channel="DIO2.020" />
            <channelpin enabled="true" pin="TEST_IO31" channel="DIO2.063" />
            <channelpin enabled="true" pin="TEST_IO34" channel="DIO2.056" />
            <channelpin enabled="true" pin="TEST_IO40" channel="DIO2.075" />
            <channelpin enabled="true" pin="TEST_IO47" channel="DIO2.074" />
            <channelpin enabled="true" pin="TEST_IO5" channel="DIO2.101" />
            <channelpin enabled="true" pin="TEST_IO4" channel="DIO2.113" />
            <channelpin enabled="true" pin="TEST_IO6" channel="DIO2.100" />
            <channelpin enabled="true" pin="TEST_IO9" channel="DIO2.094" />
            <channelpin enabled="true" pin="TEST_IO8" channel="DIO2.112" />
            <channelpin enabled="true" pin="TEST_IO7" channel="DIO2.107" />
            <channelpin enabled="true" pin="TEST_IO12" channel="DIO2.119" />
            <channelpin enabled="true" pin="TEST_IO11" channel="DIO2.106" />
            <channelpin enabled="true" pin="TEST_IO10" channel="DIO2.024" />
            <channelpin enabled="true" pin="TEST_IO15" channel="DIO2.018" />
            <channelpin enabled="true" pin="TEST_IO14" channel="DIO2.025" />
            <channelpin enabled="true" pin="TEST_IO13" channel="DIO2.095" />
            <channelpin enabled="true" pin="TEST_IO18" channel="DIO2.030" />
            <channelpin enabled="true" pin="TEST_IO17" channel="DIO2.088" />
            <channelpin enabled="true" pin="TEST_IO16" channel="DIO2.118" />
            <channelpin enabled="true" pin="TEST_IO21" channel="DIO2.089" />
            <channelpin enabled="true" pin="TEST_IO20" channel="DIO2.125" />
            <channelpin enabled="true" pin="TEST_IO19" channel="DIO2.019" />
            <channelpin enabled="true" pin="TEST_IO24" channel="DIO2.124" />
            <channelpin enabled="true" pin="TEST_IO23" channel="DIO2.013" />
            <channelpin enabled="true" pin="TEST_IO22" channel="DIO2.031" />
            <channelpin enabled="true" pin="TEST_IO27" channel="DIO2.012" />
            <channelpin enabled="true" pin="TEST_IO26" channel="DIO2.050" />
            <channelpin enabled="true" pin="TEST_IO25" channel="DIO2.036" />
            <channelpin enabled="true" pin="TEST_IO30" channel="DIO2.037" />
            <channelpin enabled="true" pin="TEST_IO29" channel="DIO2.082" />
            <channelpin enabled="true" pin="TEST_IO28" channel="DIO2.007" />
            <channelpin enabled="true" pin="TEST_IO33" channel="DIO2.042" />
            <channelpin enabled="true" pin="TEST_IO32" channel="DIO2.006" />
            <channelpin enabled="true" pin="TEST_IO36" channel="DIO2.001" />
            <channelpin enabled="true" pin="TEST_IO35" channel="DIO2.051" />
            <channelpin enabled="true" pin="TEST_IO39" channel="DIO2.000" />
            <channelpin enabled="true" pin="TEST_IO38" channel="DIO2.057" />
            <channelpin enabled="true" pin="TEST_IO37" channel="DIO2.043" />
            <channelpin enabled="true" pin="TEST_IO42" channel="DIO2.048" />
            <channelpin enabled="true" pin="TEST_IO41" channel="DIO2.070" />
            <channelpin enabled="true" pin="TEST_IO46" channel="DIO2.064" />
            <channelpin enabled="true" pin="TEST_IO45" channel="DIO2.054" />
            <channelpin enabled="true" pin="TEST_IO44" channel="DIO2.071" />
            <channelpin enabled="true" pin="TEST_IO43" channel="DIO2.049" />
            <channelpin enabled="true" pin="TEST_IO49" channel="DIO2.058" />
            <channelpin enabled="true" pin="TEST_IO48" channel="DIO2.055" />
            <channelpin enabled="true" pin="TEST_IO50" channel="DIO2.065" />
            <channelpin enabled="true" pin="CLOCK_OUT_A" channel="DIO2.076" />
            <channelpin enabled="true" pin="CLOCK_OUT_B" channel="DIO2.083" />
            <channelpin enabled="true" pin="CLOCK_OUT_C" channel="DIO2.077" />
            <channelpin enabled="true" pin="CORNER_TL" channel="DIO1.071" />
            <channelpin enabled="true" pin="CORNER_BL" channel="DIO1.011" />
            <channelpin enabled="true" pin="CORNER_TR" channel="DIO7.212" />
            <channelpin enabled="true" pin="CORNER_BR" channel="DIO2.080" />
            <channelpin enabled="true" pin="LED_DATA" channel="DIO2.251" />
            <channelpin enabled="true" pin="LED_CLOCK" channel="DIO2.250" />
            <channelpin enabled="true" pin="OVER_TEMP" channel="DIO2.244" />
            <channelpin enabled="true" pin="FMAG_SYN_CLK0" channel="DIO2.245" />
            <channelpin enabled="true" pin="FMAG_SYN_CLK1" channel="DIO2.232" />
            <channelpin enabled="true" pin="FMAG_SYN_CLK2" channel="DIO2.238" />
            <channelpin enabled="true" pin="FMAG_NG_TSYNC_FRAME" channel="DIO2.239" />
            <channelpin enabled="true" pin="TVS0_CAL_TEST0" channel="DIO2.227" />
            <channelpin enabled="true" pin="TVS0_CAL_TEST1" channel="DIO2.138" />
            <channelpin enabled="true" pin="TVS0_CAL_TEST2" channel="DIO2.133" />
            <channelpin enabled="true" pin="TVS1_CAL_TEST0" channel="DIO2.226" />
            <channelpin enabled="true" pin="TVS1_CAL_TEST1" channel="DIO2.139" />
            <channelpin enabled="true" pin="TVS1_CAL_TEST2" channel="DIO2.132" />
            <channelpin enabled="true" pin="TEST_IO0" channel="DIO2.233" />
            <channelpin enabled="true" pin="TEST_IO3" channel="DIO2.161" />
            <channelpin enabled="true" pin="TEST_IO2" channel="DIO2.167" />
            <channelpin enabled="true" pin="TEST_IO1" channel="DIO2.160" />
            <channelpin enabled="true" pin="ICP_I2C_ADDR0" channel="DIO2.198" />
            <channelpin enabled="true" pin="ICP_I2C_ADDR1" channel="DIO2.205" />
            <channelpin enabled="true" pin="ICP_I2C_ADDR2" channel="DIO2.204" />
            <channelpin enabled="true" pin="ICP_I2C_ADDR3" channel="DIO2.192" />
            <channelpin enabled="true" pin="ICP_I2C_SCL" channel="DIO2.199" />
            <channelpin enabled="true" pin="ICP_I2C_SDA" channel="DIO2.081" />
            <channelpin enabled="true" pin="PTP_I2C_SCL" channel="DIO2.066" />
            <channelpin enabled="true" pin="PTP_I2C_SDA" channel="DIO2.060" />
            <channelpin enabled="true" pin="PTP_I2C_SEC" channel="DIO2.061" />
            <channelpin enabled="true" pin="H16_CTLE_SEL0" channel="DIO2.157" />
            <channelpin enabled="true" pin="H16_CTLE_SEL1" channel="DIO2.151" />
            <channelpin enabled="true" pin="H16_CTLE_SEL2" channel="DIO2.150" />
            <channelpin enabled="true" pin="VID0" channel="DIO2.187" />
            <channelpin enabled="true" pin="VID1" channel="DIO2.174" />
            <channelpin enabled="true" pin="VID2" channel="DIO2.181" />
            <channelpin enabled="true" pin="VID3" channel="DIO2.175" />
            <channelpin enabled="true" pin="VID4" channel="DIO2.168" />
            <channelpin enabled="true" pin="VID5" channel="DIO2.156" />
            <channelpin enabled="true" pin="VID6" channel="DIO2.180" />
            <channelpin enabled="true" pin="VID7" channel="DIO2.186" />
            <channelpin enabled="true" pin="AVS_PMB_SDA" channel="DIO2.169" />
            <channelpin enabled="true" pin="AVS_PMB_SCL" channel="DIO2.162" />
            <channelpin enabled="true" pin="AVS_PMB_ALERT_N" channel="DIO2.163" />
            <channelpin enabled="true" pin="SYS_RST_N" channel="DIO2.062" />
            <channelpin enabled="true" pin="PCIE_INT_N" channel="DIO2.193" />
            <channelpin enabled="true" pin="SYS_REF_CLK_SEL" channel="DIO2.068" />
            <channelpin enabled="true" pin="SYS_REF_CLK_BAK" channel="DIO2.069" />
            <channelpin enabled="true" pin="SYS_REF_CLK_P" channel="DIO7.042" />
            <channelpin enabled="true" pin="SYS_REF_CLK_N" channel="DIO7.043" />
            <channelpin enabled="true" pin="FMAG_REF_CLK0_P" channel="DIO7.114" />
            <channelpin enabled="true" pin="FMAG_REF_CLK0_N" channel="DIO7.115" />
            <channelpin enabled="true" pin="FMAG_REF_CLK1_P" channel="DIO7.128" />
            <channelpin enabled="true" pin="FMAG_REF_CLK1_N" channel="DIO7.129" />
            <channelpin enabled="true" pin="LMAG_REF_CLK_P" channel="DIO7.254" />
            <channelpin enabled="true" pin="LMAG_REF_CLK_N" channel="DIO7.255" />
            <channelpin enabled="true" pin="REL_CTRL1" channel="U0.0" />
            <channelpin enabled="true" pin="REL_CTRL2" channel="U0.1" />
            <channelpin enabled="true" pin="REL_CTRL3" channel="U0.2" />
            <channelpin enabled="true" pin="REL_CTRL4" channel="U0.3" />
            <channelpin enabled="true" pin="REL_CTRL5" channel="U0.4" />
            <channelpin enabled="true" pin="REL_CTRL6" channel="U0.5" />
            <channelpin enabled="true" pin="LJC1_UDB0" channel="U0.6" />
            <channelpin enabled="true" pin="LJC1_UDB1" channel="U0.7" />
            <channelpin enabled="true" pin="CLK_SEL_CBIT1" channel="U0.8" />
            <channelpin enabled="true" pin="UDB_K1" channel="U0.9" />
            <channelpin enabled="true" pin="UDB_K2" channel="U0.10" />
            <channelpin enabled="true" pin="UDB_K3" channel="U0.11" />
            <channelpin enabled="true" pin="VSS_DVDD12_TEST" channel="DIO2.184" />
            <channelpin enabled="true" pin="HVCC_H30_TEST" channel="DIO2.172" />
            <channelpin enabled="true" pin="VSS_HVCC_H30_TEST" channel="DIO2.173" />
            <channelpin enabled="true" pin="LVCC_H30_TEST" channel="DIO7.035" />
            <channelpin enabled="true" pin="VSS_LVCC_H30_TEST" channel="DIO7.034" />
            <channelpin enabled="true" pin="VDDIO12_DDR_TEST" channel="DIO2.197" />
            <channelpin enabled="true" pin="VSS_VDDIO_DDR_TEST" channel="DIO2.196" />
            <channelpin enabled="true" pin="DVDD_TEST" channel="DIO2.185" />
            <channelpin enabled="true" pin="PCM1_CLKIN1" channel="DIO1.064" />
            <channelpin enabled="true" pin="PCM1_CS" channel="DIO1.021" />
            <channelpin enabled="true" pin="PCM1_SCK" channel="DIO1.014" />
            <channelpin enabled="true" pin="PCM1_SDAIO" channel="DIO1.020" />
            <channelpin enabled="true" pin="PCM1_SDO" channel="DIO1.015" />
            <channelpin enabled="true" pin="PCM1_NC_Status_LD1" channel="DIO1.027" />
            <channelpin enabled="true" pin="PCM1_NC_Status_LD2" channel="DIO1.026" />
            <channelpin enabled="true" pin="PCM1_CLKIN1N" channel="DIO1.033" />
            <channelpin enabled="true" pin="PCM1_CLKIN1P" channel="DIO1.032" />
        </channelpins>
    </channelmap>
</channelmaps>
